### ISSUE TITLE
Fix compiling error 134:16: error: 'esp_lcd_dpi_panel_event_callbacks_t' has no member named 'on_frame_buf_complete'

### ISSUE THREAD

**Issue by henocgimeno-prog** [trailcurrentoss/TrailCurrentFluidCNCPendant#1]
Hello,

If you have this error (esp_lcd_dpi_panel_event_callbacks_t' has no member named 'on_frame_buf_complete) when following the instructions, it can be easily fixed by adding:

**espressif/esp_lvgl_port:
    version: "==2.8.0"**

to the idf_component_yml in case you are using IDF 5.5.2. I have not been able to compile using IDF 6.0.2 

Reason is:
-------------
   Pinned EXACT: 2.9.0 guards its DPI vsync callback with
   `#if ESP_IDF_VERSION >= ESP_IDF_VERSION_VAL(5, 5, 0)` and assumes IDF 5.5
   renamed `on_refresh_done` -> `on_frame_buf_complete` in
   esp_lcd_dpi_panel_event_callbacks_t. That rename only ever landed on an
   IDF master snapshot; the actual 5.5.2 and 6.0.2 headers installed here
   still use `on_refresh_done`, so 2.9.0 fails to compile with
   "has no member named 'on_frame_buf_complete'". 2.8.0 predates that
   (broken) guard and uses `on_refresh_done` unconditionally.
  -------------

I hope this can help someone.
